version: 2
jobs:
  build_and_test:
    working_directory: /
    docker:
        - image: circleci/golang:1.13
    steps:
      - run:
          name: Install tracer
          command: go get github.com/edison-moreland/tracer.go/cmd/demo

      - run:
          name: Render demo scene
          command: demo

      - store_artifacts:
          path: /traced.png
